Update non working links
Clinify-Open-Sauce/CPC-Programs pull request #2
Opened 2021-05-25 09:50 UTC by iamjoker021

Most of links were directed to 404 error

I have updated the links in readme.md so that they could direct to desired page

2021-05-25 10:52 UTC, Zircoz requested changes
For internal links, can you please make them relative paths instead ? That will prevent them from breaking if this repo's address or name changes later.

2021-05-26 04:28 UTC, iamjoker021 commented
I have changed relative path for Contributing.md and LICENSE instead of links

I'm new to GitHub so I didn't know whether there is relative paths exists for forks, stars etc.

2021-05-26 07:45 UTC, Zircoz approved these changes

2021-05-26 07:46 UTC, merged

2021-05-26 07:46 UTC, Zircoz commented
thanks for contributing @iamjoker021 !:D